### ISSUE TITLE
Can't send mail items

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-premium#10]
> When player trying to use in-game email via Premium command, nothing happen. U can't send or receive mail items or etc trough premium option.
> 
> Mail should work any other out there.

From here since the guy is too lazy to do it... https://github.com/azerothcore/azerothcore-wotlk/issues/888

@knindzagxg

**Comment by pangolp** [comment]
I think this bug has already been resolved. In any case, if it persists, we will make another pull request that is a little more updated.
