### ISSUE TITLE
Searches wrong config

### ISSUE THREAD

**Issue by Rochet2** [azerothcore/mod-premium#12]
https://github.com/azerothcore/mod-premium/blob/23330eae3dccf1dcaa25f2fc9e58ef8e05000b47/src/premium.cpp#L336-L342

windows is coded to search for different config than linux

**Comment by talamortis** [comment]
https://github.com/azerothcore/mod-premium/commit/022c4413b7979947b6b568ea6d6610deecb73557 fixed.
