### ISSUE TITLE
Compile warnings after last core updates.

### ISSUE THREAD

**Issue by Nemepy** [azerothcore/mod-premium#5]
/home/wow/azerothcore/modules/mod-premium/src/premium.cpp:311:31: warning: unused variable 'trainer' [-Wunused-variable]
                    Creature* trainer = player->SummonCreature(HMAGE, player->GetPositionX(), player->GetPositionY(), player->GetPosition...
                              ^
/home/wow/azerothcore/modules/mod-premium/src/premium.cpp:317:31: warning: unused variable 'trainer' [-Wunused-variable]
                    Creature* trainer = player->SummonCreature(APALADIN, player->GetPositionX(), player->GetPositionY(), player->GetPosit..

and many others

**Comment by talamortis** [comment]
Thanks for this i will take a look tomorrow and fix the issue 👍

**Comment by talamortis** [comment]
please test now :)
