### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by luisforte** [azerothcore/mod-premium#6]
Compiled with latest core and not working.
No errors in build but the script doesn't trigger in-game

**Comment by talamortis** [comment]
did you apply the script to an item?

**Comment by luisforte** [comment]
Yes of coarse... hearthstone and other itens.... not working

2018-01-08 5:54 GMT-02:00 Lee <notifications@github.com>:

**Comment by luisforte** [comment]
Fixed... i dont know hy, but after Host full reboot the module comes working. Thanks Talamortis!
